# Generated by Django 5.2 on 2025-05-05 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='ID format: [0-8]mp23[dept_code][3 digits] for students/teachers, or admin[3 digits] for admin', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid ID format. Must be like: 1mp23cs001 for students, 0mp23cs001 for teachers, or admin001 for admin', regex='^(admin\\d{3}|[0-8]mp23(cg|cs|is|ml|ds)\\d{3})$')]),
        ),
    ]
