# Generated by Django 5.2 on 2025-05-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_picture_alter_user_role_and_more'),
        ('accounts', '0003_create_student_teacher_models'),
    ]

    operations = [
    ]
