# Generated by Django 5.2.1 on 2025-05-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
