# Generated by Django 5.2.1 on 2025-05-07 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='exam',
            name='late_submission_end',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='5 days after end_time for late submissions'),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
