# Generated by Django 5.2.1 on 2025-05-09 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_department_alter_student_semester_and_more'),
        ('exams', '0003_department_remove_exam_updated_at_exam_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('abandoned', 'Abandoned')], default='started', max_length=20)),
                ('answers', models.JSONField(default=dict)),
                ('is_late_submission', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser_info', models.CharField(blank=True, max_length=255, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'ordering': ['-start_time'],
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
