# Generated by Django 5.2.1 on 2025-05-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examattempt'),
        ('exams', '0004_fix_department_data'),
    ]

    operations = [
    ]
