# Generated by Django 5.2.1 on 2025-05-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_department_field'),
        ('exams', '0005_merge_0004_examattempt_0004_fix_department_data'),
    ]

    operations = [
    ]
